// flow-typed signature: baf79935fcb90224e41af90e08ebfef5
// flow-typed version: <<STUB>>/react-native-svg-icon_v>=0.8.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-svg-icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-svg-icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-svg-icon/lib/components/SvgIcon' {
  declare module.exports: any;
}

declare module 'react-native-svg-icon/lib' {
  declare module.exports: any;
}

declare module 'react-native-svg-icon/src/components/SvgIcon' {
  declare module.exports: any;
}

declare module 'react-native-svg-icon/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-svg-icon/lib/components/SvgIcon.js' {
  declare module.exports: $Exports<'react-native-svg-icon/lib/components/SvgIcon'>;
}
declare module 'react-native-svg-icon/lib/index' {
  declare module.exports: $Exports<'react-native-svg-icon/lib'>;
}
declare module 'react-native-svg-icon/lib/index.js' {
  declare module.exports: $Exports<'react-native-svg-icon/lib'>;
}
declare module 'react-native-svg-icon/src/components/SvgIcon.js' {
  declare module.exports: $Exports<'react-native-svg-icon/src/components/SvgIcon'>;
}
declare module 'react-native-svg-icon/src/index' {
  declare module.exports: $Exports<'react-native-svg-icon/src'>;
}
declare module 'react-native-svg-icon/src/index.js' {
  declare module.exports: $Exports<'react-native-svg-icon/src'>;
}
