// flow-typed signature: fe69f93363c61435434ce79cd646ad96
// flow-typed version: <<STUB>>/react-native-modal-selector_v^1.1.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modal-selector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modal-selector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-modal-selector/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-modal-selector/index' {
  declare module.exports: $Exports<'react-native-modal-selector'>;
}
declare module 'react-native-modal-selector/index.js' {
  declare module.exports: $Exports<'react-native-modal-selector'>;
}
declare module 'react-native-modal-selector/style.js' {
  declare module.exports: $Exports<'react-native-modal-selector/style'>;
}
